package com.opower.rest.client.hystrix;

/**
 * Interface for handling CommandStatus updates generated by the OpowerEventNotifier. Since this interface
 * will be invoked synchronously during HystirxCommand executions, the implementations need to be
 * thread-safe and fast. Otherwise the overhead will slow down execution times for the HystrixCommands. If
 * the work to handle the CommandStatus is slow it should be performed asynchronously.
 * @author chris.phillips
 */
public interface CommandStatusListener {

    /**
     * Proccess the provided CommandStatus. 
     * @param commandStatus the CommandStatus to process.
     */
    void handleCommandStatus(CommandStatus commandStatus);
}
